### PR TITLE
Added protocol for Eco

### PR DESCRIPTION
**Pull request by behesse**
Hi,

I was in need for support for the game "Eco" from SLG (https://play.eco/) and thought, it may be useful for others too. 
Maybe you can take a look at it.

Thanks,
Ben

### CODE REVIEW

**Comment by xLeviNx** [comment]
Hey, have you tested an eco server after this implementation?

**Comment by behesse** [comment]
I tested with some random servers of the masterlist ( http://masterserver.eco.strangeloopgames.com/api/v1/ServerListing ). ADDRESS:WEBPORT are the correct parameters for the "query connection".

**Comment by xLeviNx** [comment]
Can attest this works great, nice work!

**Review by xLeviNx — APPROVED** [review]

**Comment by BattlefieldDuck** [comment]
> Hi,
> 
> I was in need for support for the game "Eco" from SLG (https://play.eco/) and thought, it may be useful for others too. Maybe you can take a look at it.
> 
> Thanks, Ben

thank you!

**Pull request merged**
